# Generated by Django 5.2.6 on 2025-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('rua', models.TextField(max_length=255)),
                ('bairro', models.TextField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cadastro',
            },
        ),
    ]
